project:
  type: website
  output-dir: ../docs          # write HTML into docs/

website:
  title: "<img src='images/dottori_lab_pentagon.svg' height='32' style='vertical-align: middle; margin-right: 0.5em;'> FRDA Transcriptomic Atlas Handbook"
  site-url: "https://marniemaddock.github.io/FRDATranscriptomicAtlas/"
  favicon: favicon.ico
  navbar:
    left:
      - text: "Overview"
        file: overview.qmd

      - text: "Download"
        file: local_access.qmd

      - text: "Features"
        file: how_to_use.qmd

      - text: "Version History"
        file: version_history.qmd

      - text: "Feature Requests"
        file: features_issues.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    css: styles.css
    include-in-header:
      text: |
        <meta name="google-site-verification" content="Yl5oJWY-HTVA-q5QncfpMR0TLVEtV9MNmGy8dbswmIM" />
