---
title: "Feature Requests and Issues"
---
If you have found this app useful, please consider reaching out to out team to share your feedback, suggestions, or any questions you may have. We are committed to improving this resource and your input is invaluable in guiding future updates and features.

If you'd like to request a new feature, suggestions or report an issue/bug, please submit it on GitHub: [GitHub Issues](https://github.com/MarnieMaddock/FRDATranscriptomicAtlas/issues). Please include as much detail as possible to help us address your request effectively.

For information about this resource, first consult the publication:

Friedreich ataxia transcriptomic dysregulation and identification of cell type-specific biomarkers: A systematic review and meta-analysis

Marnie L. Maddock, Sara Miellet, Anjila Dongol, Amy J. Hulme, Chloe K. Kennedy, Louise A. Corben, Rocio K. Finol-Urdaneta, Alberto Nettel-Aguirre, Chiara Dionisi, Martin B. Delatycki, Joel M. Gottesfeld, Massimo Pandolfo, Elisabetta Soragni, Sanjay I. Bidichandani, Jarmon G. Lees, Shiang Y. Lim, Jill S. Napierala, Marek Napierala, Mirella Dottori

bioRxiv 2026.03.18.712785; doi: <https://doi.org/10.64898/2026.03.18.712785>


For further information, or clarification on how to use the app, please contact the [developers](mailto:mlm715@uowmail.edu.au?subject=FRDATranscriptomicAtlas%20Query:).

