# R/deps.R — help rsconnect detect dependencies
library(shiny); library(shinyjs); library(bslib); library(DT)
library(ggplot2); library(ggpubr); library(ggbeeswarm); library(ggtext)
library(dplyr); library(tidyr); library(purrr); library(stringr)
library(plotly); library(shinyWidgets); library(shinycssloaders)
library(svglite); library(FNN); library(tibble); library(readr)
library(htmlwidgets); library(ggVennDiagram); library(heatmaply)
library(ComplexHeatmap); library(circlize); library(scales)
library(ggrepel); library(memoise); library(ragg); library(fontawesome)
library(shinyBS); library(metafor); library(rlang)
